// Stage 2 of the esctest failure pipeline: pure transformation over the stage-1 index.
// Reads docs/audit/esctest-failing-index.md, reads each test body at its file:line, extracts the
// DECSET/DECRESET/DECRQM mode arguments, resolves them through esccmd.py, and classifies each test
// against the modes this repo implements. No backslashes and no regex: path and text handling only.
import fs from 'node:fs';
import path from 'node:path';

const NL = String.fromCharCode(10);
const CR = String.fromCharCode(13);
const strip = (l) => (l.endsWith(CR) ? l.slice(0, -1) : l);
const root = 'C:/Users/z5075/AppData/Local/Temp/termai-conformance-upstream/esctest2/esctest';
const testsDir = root + '/tests';

const indexLines = fs.readFileSync('docs/audit/esctest-failing-index.md', 'utf8').split(NL).map(strip);
const rows = [];
for (const line of indexLines) {
  if (!line.startsWith('| ') || line.startsWith('| test ')) continue;
  const parts = line.split('|').map((s) => s.trim());
  const test = parts[1];
  const loc = parts[2];
  if (!test || !loc || loc.indexOf('---') >= 0) continue;
  if (loc.indexOf('UNRESOLVED') >= 0) continue;
  const bits = loc.split(':');
  rows.push({ test: test, file: bits[0], line: Number(bits[1]) });
}

const isNum = (s) => s.length > 0 && [...s].every((c) => c >= '0' && c <= '9');
const modeOf = new Map();
const esccmdRaw = fs.readFileSync(root + '/esccmd.py', 'utf8').split(NL).map(strip);
for (const l of esccmdRaw) {
  const eq = l.indexOf('=');
  if (eq < 0 || l.startsWith('#')) continue;
  const name = l.slice(0, eq).trim();
  let val = l.slice(eq + 1);
  const hash = val.indexOf('#');
  if (hash >= 0) val = val.slice(0, hash);
  val = val.trim();
  if (name && isNum(val)) modeOf.set(name, Number(val));
}
// Some modes are functions rather than constants (for example ReverseWraparound).
for (let k = 0; k < esccmdRaw.length; k += 1) {
  if (!esccmdRaw[k].startsWith('def ')) continue;
  const nm = esccmdRaw[k].slice(4).split('(')[0].trim();
  for (let j = k + 1; j < Math.min(k + 4, esccmdRaw.length); j += 1) {
    const rr = esccmdRaw[j].trim();
    if (!rr.startsWith('return ')) continue;
    const v = rr.slice(7).trim();
    if (isNum(v)) modeOf.set(nm, Number(v));
    break;
  }
}

const IMPLEMENTED = new Set([1, 4, 6, 7, 25, 47, 1047, 1049, 2004]);
const CALLS = ['DECSET(', 'DECRESET(', 'DECRQM('];
const out = [];
const modeTally = new Map();
let unimpl = 0, core = 0, noCalls = 0, unresolved = 0;

for (const r of rows) {
  const all = fs.readFileSync(path.join(testsDir, r.file), 'utf8').split(NL).map(strip);
  let end = all.length;
  for (let k = r.line; k < all.length; k += 1) {
    if (k > r.line && (all[k].startsWith('  def ') || all[k].startsWith('def '))) { end = k; break; }
  }
  const body = all.slice(r.line - 1, end);
  const modes = new Set();
  let sawCall = false;
  for (const l of body) {
    for (const call of CALLS) {
      let at = l.indexOf(call);
      while (at >= 0) {
        sawCall = true;
        const close = l.indexOf(')', at);
        const arg = close > at ? l.slice(at + call.length, close) : '';
        const dot = arg.indexOf('esccmd.');
        if (dot >= 0) {
          let name = arg.slice(dot + 7);
          for (const c of [',', ')', '(', ' ', ']']) {
            const cut = name.indexOf(c);
            if (cut >= 0) name = name.slice(0, cut);
          }
          if (modeOf.has(name)) modes.add(modeOf.get(name));
        }
        at = l.indexOf(call, at + 1);
      }
    }
  }
  const list = [...modes].sort((a, b) => a - b);
  let cls;
  if (list.some((m) => !IMPLEMENTED.has(m))) { cls = 'uses-unimplemented-mode'; unimpl += 1; }
  else if (!sawCall) { cls = 'no-extension-mode'; noCalls += 1; core += 1; }
  else { cls = 'no-extension-mode'; core += 1; }
  console.log('unused'); // placeholder removed below
  out.push({ test: r.test, modes: list, cls: cls });
}
for (const o of out) {
  if (o.cls !== 'uses-unimplemented-mode') continue;
  for (const m of o.modes) {
    if (IMPLEMENTED.has(m)) continue;
    modeTally.set(m, (modeTally.get(m) || 0) + 1);
  }
}
const top = [...modeTally.entries()].sort((a, b) => b[1] - a[1]).slice(0, 10);

const doc = [];
doc.push('# esctest classification (pipeline stage 2)');
doc.push('');
doc.push('> Generated by tools/conformance/classify-esctest.mjs over docs/audit/esctest-failing-index.md.');
doc.push('> Implementation set read from crates/termai-vt/src/grid.rs (set_private_mode / set_standard_mode):');
doc.push('> private 1/6/7/25/47/1047/1049/2004, standard 4.');
doc.push('');
doc.push('- tests classified: ' + out.length);
doc.push('- uses-unimplemented-mode: ' + unimpl);
doc.push('- no-extension-mode (core-defect candidates): ' + core + ' (of which ' + noCalls + ' make no DECSET/DECRESET/DECRQM call at all)');
doc.push('- unresolved: ' + unresolved);
doc.push('');
doc.push('## Top unimplemented modes among failing tests');
doc.push('');
doc.push('| mode | failing tests citing it |');
doc.push('| --- | --- |');
for (const t of top) doc.push('| ' + t[0] + ' | ' + t[1] + ' |');
doc.push('');
doc.push('## Core-defect candidates (no unimplemented mode cited)');
doc.push('');
doc.push('| test | modes cited |');
doc.push('| --- | --- |');
for (const o of out) if (o.cls === 'no-extension-mode') doc.push('| ' + o.test + ' | ' + (o.modes.length ? o.modes.join(', ') : '-') + ' |');
doc.push('');
fs.writeFileSync('docs/audit/esctest-classification.md', doc.join(NL) + NL);
console.log('classified=' + out.length + ' unimpl=' + unimpl + ' core=' + core + ' top=' + JSON.stringify(top));
