// Stage 1 of the esctest failure pipeline (plan section 6.3 rule 9): the lead builds the
// index, so a later workstream only has to do a pure transformation.
//
// Reads a run log, extracts the failing test names, and locates each test function in the
// esctest checkout without guessing the class->file mapping: it searches every tests/*.py.
import fs from 'node:fs';
import path from 'node:path';

const NL = String.fromCharCode(10);
const CR = String.fromCharCode(13);
const logPath = process.argv[2] || 'target/conformance/esctest-args/esctest.log';
const testsDir = process.argv[3] || 'C:/Users/z5075/AppData/Local/Temp/termai-conformance-upstream/esctest2/esctest/tests';
const outPath = process.argv[4] || 'docs/audit/esctest-failing-index.md';

const strip = (l) => (l.endsWith(CR) ? l.slice(0, -1) : l);
const raw = fs.readFileSync(logPath, 'utf8').split(NL).map(strip);
const names = [];
for (const line of raw) {
  if (line.startsWith('*** TEST ') && line.endsWith(' FAILED:')) {
    names.push(line.slice('*** TEST '.length, line.length - ' FAILED:'.length));
  }
}
const unique = [...new Set(names)].sort();

const files = fs.readdirSync(testsDir).filter((f) => f.endsWith('.py'));
const texts = new Map(files.map((f) => [f, fs.readFileSync(path.join(testsDir, f), 'utf8').split(NL).map(strip)]));

const rows = [];
let resolved = 0;
for (const full of unique) {
  const short = full.split('.').pop();
  let hit = null;
  for (const f of files) {
    const lines = texts.get(f);
    const idx = lines.findIndex((l) => l.startsWith('  def ' + short + '(') || l.startsWith('def ' + short + '('));
    if (idx >= 0) { hit = f + ':' + (idx + 1); break; }
  }
  if (hit) resolved += 1;
  rows.push('| ' + full + ' | ' + (hit || '**UNRESOLVED**') + ' |');
}

const head = [
  '# esctest failing-test index (pipeline stage 1)',
  '',
  '> Generated by node tools/conformance/failing-index.mjs. Stage 1 of plan section 6.3 rule 9:',
  '> the lead builds the index so a later workstream only does a pure transformation',
  '> (read the function body at the given file:line and extract the DECSET/DECRESET/DECRQM modes).',
  '',
  '- log: ' + logPath,
  '- failing test names: ' + unique.length + ' (deduplicated)',
  '- located in tests/*.py: ' + resolved + ' / ' + unique.length,
  '',
  '| test | file:line |',
  '| --- | --- |',
];
fs.writeFileSync(outPath, head.concat(rows).join(NL) + NL);
console.log('names=' + unique.length + ' resolved=' + resolved + ' unresolved=' + (unique.length - resolved));
console.log('wrote ' + outPath);
