#!/usr/bin/env node
// tools/conformance/gen-ctlseqs.mjs
//
// Generate the xterm ctlseqs case set (AR-31 item 1: "at least one case per ctlseqs
// entry") and the checked-in entry registry.
//
//   node tools/conformance/gen-ctlseqs.mjs --source <ctlseqs.txt> [--url <url>]
//   node tools/conformance/gen-ctlseqs.mjs --source <ctlseqs.txt> --check
//
// The generated .trec bodies carry no expected output: they are structural-invariant
// cases (oracle = "invariant", gating = false). They build the entry <-> case mapping
// and the coverage number; they are NOT an xterm compatibility oracle. Hand-authored
// cases with real expectations live in cases/xterm-ctlseqs-spec/.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseCtlseqs, entryId, sha256Hex } from './lib/ctlseqs.mjs';
import { canonicalJson } from './lib/report.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const DEFAULT_ROOT = path.resolve(HERE, '..', '..');

function parseArgs(argv) {
  const out = { source: null, url: '', check: false };
  for (const arg of argv) {
    if (arg === '--check') out.check = true;
    else if (arg.indexOf('--source=') === 0) out.source = arg.slice(9);
    else if (arg.indexOf('--url=') === 0) out.url = arg.slice(6);
    else if (arg === '--source') out.expectSource = true;
    else if (out.expectSource) { out.source = arg; out.expectSource = false; }
  }
  return out;
}

function trecEscapeKey(bytes) {
  let out = '"';
  for (const byte of bytes) out += '\\x' + byte.toString(16).padStart(2, '0');
  return out + '"';
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (!args.source) {
    console.error('usage: node tools/conformance/gen-ctlseqs.mjs --source <ctlseqs.txt> [--url <url>] [--check]');
    process.exit(2);
  }
  const sourcePath = path.resolve(args.source);
  const raw = fs.readFileSync(sourcePath, 'binary');
  const sha = sha256Hex(raw);
  const parsed = parseCtlseqs(raw);

  const dataDir = path.join(HERE, 'data');
  const suiteDir = path.join(HERE, 'cases', 'xterm-ctlseqs');
  const registry = {
    source: {
      name: path.basename(sourcePath),
      url: args.url || '',
      sha256: sha,
      bytes: raw.length,
      xterm_patch: parsed.patch,
      xterm_updated: parsed.updated,
    },
    counts: {
      raw_entry_lines: parsed.raw_entry_lines,
      entries: parsed.entries.length,
      resolved: parsed.entries.filter(function (e) { return e.complete; }).length,
      unresolved: parsed.entries.filter(function (e) { return !e.complete; }).length,
    },
    entries: parsed.entries.map(function (e) {
      return {
        id: entryId(e),
        pattern: e.pattern,
        resolved_pattern: e.resolved_pattern,
        resolved: e.complete,
        seq_hex: e.complete ? e.seq_hex : null,
        mnemonic: e.mnemonic,
        doc_line: e.doc_line,
        leftover: e.leftover,
      };
    }),
  };

  const indexLines = [];
  const bodies = new Map();
  for (const entry of registry.entries) {
    if (!entry.resolved) continue;
    const body =
      '# generated by tools/conformance/gen-ctlseqs.mjs - do not edit by hand\n' +
      '# entry: ' + entry.pattern + (entry.mnemonic ? ' (' + entry.mnemonic + ')' : '') +
      '  [ctlseqs.txt:' + entry.doc_line + ']\n' +
      '# oracle: invariant (structure only; this is NOT an xterm compatibility oracle)\n' +
      'KEY ' + trecEscapeKey(Buffer.from(entry.seq_hex, 'hex')) + '\n' +
      'KEY "\\x18"\n';
    bodies.set(entry.id + '.trec', body);
    indexLines.push(JSON.stringify({
      id: entry.id,
      suite: 'xterm-ctlseqs',
      lane: 'L0',
      oracle: 'invariant',
      gating: false,
      cols: 80,
      rows: 24,
      ctlseqs_entry: entry.resolved_pattern,
      ctlseqs_mnemonic: entry.mnemonic,
      documented: 'ctlseqs.txt:' + entry.doc_line,
      real_corpus: false,
      note: 'structural-invariant coverage case; expectations are kernel/01 K-06/K-03 invariants, not xterm behaviour',
    }));
  }
  indexLines.sort();

  if (args.check) {
    const problems = [];
    const registryPath = path.join(dataDir, 'ctlseqs-entries.json');
    if (!fs.existsSync(registryPath)) problems.push('missing ' + registryPath);
    else if (fs.readFileSync(registryPath, 'utf8') !== canonicalJson(registry)) {
      problems.push('data/ctlseqs-entries.json is stale');
    }
    const indexPath = path.join(suiteDir, 'index.jsonl');
    const wanted = indexLines.join('\n') + '\n';
    if (!fs.existsSync(indexPath)) problems.push('missing ' + indexPath);
    else if (fs.readFileSync(indexPath, 'utf8') !== wanted) problems.push('cases/xterm-ctlseqs/index.jsonl is stale');
    for (const name of bodies.keys()) {
      const p = path.join(suiteDir, name);
      if (!fs.existsSync(p) || fs.readFileSync(p, 'utf8') !== bodies.get(name)) {
        problems.push('stale or missing case body ' + name);
      }
    }
    if (problems.length) {
      console.log('gen-ctlseqs --check FAIL');
      for (const p of problems) console.log('  - ' + p);
      process.exit(1);
    }
    console.log('gen-ctlseqs --check PASS (' + bodies.size + ' generated cases match the registry)');
    return;
  }

  fs.mkdirSync(dataDir, { recursive: true });
  fs.mkdirSync(suiteDir, { recursive: true });
  fs.writeFileSync(path.join(dataDir, 'ctlseqs-entries.json'), canonicalJson(registry));
  fs.writeFileSync(path.join(suiteDir, 'index.jsonl'), indexLines.join('\n') + '\n');
  for (const [name, body] of bodies) fs.writeFileSync(path.join(suiteDir, name), body);

  console.log('gen-ctlseqs: source=' + registry.source.name + ' sha256=' + sha.slice(0, 16) + '...');
  console.log('  xterm patch: #' + String(registry.source.xterm_patch) + ' (' + String(registry.source.xterm_updated) + ')');
  console.log('  raw entry lines: ' + registry.counts.raw_entry_lines);
  console.log('  unique entries:  ' + registry.counts.entries);
  console.log('  resolved:        ' + registry.counts.resolved);
  console.log('  unresolved:      ' + registry.counts.unresolved);
  console.log('  generated cases: ' + bodies.size);
  const unresolved = registry.entries.filter(function (e) { return !e.resolved; });
  if (unresolved.length) {
    console.log('  unresolved entries (no case generated, listed for honesty):');
    for (const e of unresolved) {
      console.log('    - ctlseqs.txt:' + e.doc_line + ' [' + e.pattern + '] leftover="' + e.leftover + '"');
    }
  }
}

main();
