//! AUTO-GENERATED by tools/tokens/build.mjs - DO NOT EDIT.
//! TermAI design tokens (DC-09 / AR-22). Leaf crate: no dependencies.
#![no_std]
#![forbid(unsafe_code)]
// Generated file: keep rustfmt out of it (regenerate instead of reformatting).
#![cfg_attr(rustfmt, rustfmt::skip)]

/// Active theme. Default is follow-system, falling back to dark (AR-23 item 7).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Theme {
    Dark,
    Light,
}

impl Theme {
    pub const ALL: [Theme; 2] = [Theme::Dark, Theme::Light];

    pub const fn id(self) -> &'static str {
        match self {
            Theme::Dark => "dark",
            Theme::Light => "light",
        }
    }

    /// System preference could not be determined -> dark.
    pub const fn fallback() -> Theme {
        Theme::Dark
    }
}

/// A token: kebab-case name (equal to the CSS custom property without the leading --).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Token {
    pub name: &'static str,
    pub value: &'static str,
}

/// Resolved dark theme values.
pub const DARK: &[Token] = &[
    Token { name: "canvas", value: "#08090C" },
    Token { name: "surface", value: "#17191F" },
    Token { name: "raised", value: "#1E2129" },
    Token { name: "sunken", value: "#121419" },
    Token { name: "border", value: "#2A2F38" },
    Token { name: "border-soft", value: "#20242C" },
    Token { name: "text", value: "#E7E9EE" },
    Token { name: "text-2", value: "#A6ADBA" },
    Token { name: "text-3", value: "#949CAA" },
    Token { name: "ghost", value: "#868E9C" },
    Token { name: "accent", value: "#4A9EFF" },
    Token { name: "accent-ink", value: "#06121F" },
    Token { name: "accent-dim", value: "rgba(74,158,255,.12)" },
    Token { name: "accent-dim2", value: "rgba(74,158,255,.20)" },
    Token { name: "accent-line", value: "rgba(74,158,255,.35)" },
    Token { name: "hover", value: "rgba(255,255,255,.045)" },
    Token { name: "hover-2", value: "rgba(255,255,255,.075)" },
    Token { name: "overlay", value: "rgba(6,7,10,.62)" },
    Token { name: "wall-a", value: "#243244" },
    Token { name: "wall-b", value: "#5D6470" },
    Token { name: "wall-c", value: "#C69A63" },
    Token { name: "wall-d", value: "#E0B478" },
    Token { name: "wall-e", value: "#8A5A2B" },
    Token { name: "mark-a", value: "#2A63D8" },
    Token { name: "mark-b", value: "#1E4FC4" },
    Token { name: "mark-c", value: "#14347F" },
    Token { name: "term-bg", value: "#0B0D11" },
    Token { name: "term-bg2", value: "#0E1116" },
    Token { name: "term-fg", value: "#C9D1DC" },
    Token { name: "term-dim", value: "#9AA4B2" },
    Token { name: "term-mut", value: "#A3ADBB" },
    Token { name: "a-red", value: "#FF6B62" },
    Token { name: "a-green", value: "#4ED17A" },
    Token { name: "a-yellow", value: "#E8B93B" },
    Token { name: "a-blue", value: "#79B8FF" },
    Token { name: "a-mag", value: "#C79BFF" },
    Token { name: "a-cyan", value: "#4FD6E0" },
    Token { name: "a-white", value: "#F0F4FA" },
    Token { name: "sel", value: "rgba(74,158,255,.28)" },
    Token { name: "sel-ink", value: "#F0F4FA" },
    Token { name: "c-green", value: "#22C55E" },
    Token { name: "c-amber", value: "#D97706" },
    Token { name: "c-red", value: "#EF4444" },
    Token { name: "c-orange", value: "#F97316" },
    Token { name: "c-blue", value: "#3B82F6" },
    Token { name: "c-purple", value: "#A855F7" },
    Token { name: "c-teal", value: "#14B8A6" },
    Token { name: "c-slate", value: "#5B6B7C" },
    Token { name: "c-pink", value: "#EC4899" },
    Token { name: "term-line", value: "#1A1E26" },
    Token { name: "term-strong", value: "#EAF0F8" },
    Token { name: "term-metric", value: "#D3DBE6" },
    Token { name: "term-tab-ink", value: "#E1E7F0" },
    Token { name: "term-tab-on", value: "#EDF2F9" },
    Token { name: "term-tab-line", value: "#1E232C" },
    Token { name: "term-danger", value: "#FF8A80" },
    Token { name: "term-accent", value: "#8CC2FF" },
    Token { name: "term-accent-fg", value: "#6FB2FF" },
    Token { name: "term-accent-ink", value: "#EAF3FF" },
    Token { name: "term-fg-bright", value: "#E6ECF4" },
    Token { name: "term-sel-ink", value: "#F0F4FA" },
    Token { name: "ink-on-color", value: "#FFFFFF" },
    Token { name: "seg-on", value: "#262B34" },
    Token { name: "wc-close", value: "#FF5F57" },
    Token { name: "wc-min", value: "#FEBC2E" },
    Token { name: "wc-max", value: "#28C840" },
    Token { name: "font-ui", value: "-apple-system,BlinkMacSystemFont,\"Segoe UI Variable Text\",\"Segoe UI\",Inter,system-ui,\"PingFang SC\",\"Microsoft YaHei UI\",\"Noto Sans SC\",sans-serif" },
    Token { name: "font-mono", value: "ui-monospace,\"Cascadia Mono\",\"SF Mono\",Menlo,Consolas,\"JetBrains Mono\",monospace" },
    Token { name: "fs-12", value: "12px" },
    Token { name: "fs-13", value: "13px" },
    Token { name: "fs-14", value: "14px" },
    Token { name: "fs-15", value: "15px" },
    Token { name: "fs-16", value: "16px" },
    Token { name: "fs-18", value: "18px" },
    Token { name: "fs-20", value: "20px" },
    Token { name: "term-fs", value: "12.5px" },
    Token { name: "term-fs-12", value: "12px" },
    Token { name: "term-fs-14", value: "14px" },
    Token { name: "term-fs-16", value: "16px" },
    Token { name: "term-fs-18", value: "18px" },
    Token { name: "term-fs-20", value: "20px" },
    Token { name: "sp-1", value: "4px" },
    Token { name: "sp-2", value: "8px" },
    Token { name: "sp-3", value: "12px" },
    Token { name: "sp-4", value: "16px" },
    Token { name: "sp-5", value: "24px" },
    Token { name: "sp-6", value: "32px" },
    Token { name: "sp-7", value: "48px" },
    Token { name: "card-head-h", value: "44px" },
    Token { name: "statusbar-h", value: "32px" },
    Token { name: "titlebar-h", value: "48px" },
    Token { name: "toolbar-h", value: "56px" },
    Token { name: "capsule-h", value: "48px" },
    Token { name: "win-mx", value: "clamp(16px,2.4vw,56px)" },
    Token { name: "win-my", value: "clamp(12px,1.7vh,24px)" },
    Token { name: "r-input", value: "8px" },
    Token { name: "r-card", value: "10px" },
    Token { name: "r-pop", value: "14px" },
    Token { name: "r-pill", value: "999px" },
    Token { name: "elev-0", value: "none" },
    Token { name: "elev-1", value: "0 1px 2px rgba(0,0,0,.34)" },
    Token { name: "elev-2", value: "0 24px 64px rgba(0,0,0,.6)" },
    Token { name: "shadow-win", value: "0 32px 90px rgba(0,0,0,.62), inset 0 1px 0 rgba(255,255,255,.04)" },
    Token { name: "m-fast", value: "120ms" },
    Token { name: "m-base", value: "180ms" },
    Token { name: "m-slow", value: "240ms" },
    Token { name: "ease", value: "cubic-bezier(.2,0,0,1)" },
    Token { name: "ease-out", value: "cubic-bezier(.25,1,.5,1)" },
    Token { name: "risk-l0", value: "#7FB8FF" },
    Token { name: "risk-l1", value: "#22C55E" },
    Token { name: "risk-l2", value: "#F0A23C" },
    Token { name: "risk-l3", value: "#FF8578" },
    Token { name: "risk-l3-ink", value: "#1A0B0A" },
    Token { name: "risk-u", value: "#C9A0FF" },
    Token { name: "code-bg", value: "rgba(74,158,255,.14)" },
    Token { name: "code-bd", value: "rgba(74,158,255,.22)" },
    Token { name: "code-fg", value: "#9CC7FF" },
];

/// Resolved light theme values.
pub const LIGHT: &[Token] = &[
    Token { name: "canvas", value: "#F6F5F2" },
    Token { name: "surface", value: "#FFFFFF" },
    Token { name: "raised", value: "#F1F0EC" },
    Token { name: "sunken", value: "#F7F7F5" },
    Token { name: "border", value: "#E6E4DF" },
    Token { name: "border-soft", value: "#EFEDE8" },
    Token { name: "text", value: "#1B1D21" },
    Token { name: "text-2", value: "#59616D" },
    Token { name: "text-3", value: "#5E6571" },
    Token { name: "ghost", value: "#7C8493" },
    Token { name: "accent", value: "#245BC9" },
    Token { name: "accent-ink", value: "#FFFFFF" },
    Token { name: "accent-dim", value: "rgba(47,111,237,.10)" },
    Token { name: "accent-dim2", value: "rgba(47,111,237,.17)" },
    Token { name: "accent-line", value: "rgba(47,111,237,.32)" },
    Token { name: "hover", value: "rgba(20,22,26,.045)" },
    Token { name: "hover-2", value: "rgba(20,22,26,.075)" },
    Token { name: "overlay", value: "rgba(48,44,38,.35)" },
    Token { name: "wall-a", value: "#7F8A94" },
    Token { name: "wall-b", value: "#BFC2BE" },
    Token { name: "wall-c", value: "#E9C79B" },
    Token { name: "wall-d", value: "#F0CFA2" },
    Token { name: "wall-e", value: "#B98A55" },
    Token { name: "mark-a", value: "#2A63D8" },
    Token { name: "mark-b", value: "#1E4FC4" },
    Token { name: "mark-c", value: "#14347F" },
    Token { name: "term-bg", value: "#0B0D11" },
    Token { name: "term-bg2", value: "#0E1116" },
    Token { name: "term-fg", value: "#C9D1DC" },
    Token { name: "term-dim", value: "#9AA4B2" },
    Token { name: "term-mut", value: "#A3ADBB" },
    Token { name: "a-red", value: "#FF6B62" },
    Token { name: "a-green", value: "#4ED17A" },
    Token { name: "a-yellow", value: "#E8B93B" },
    Token { name: "a-blue", value: "#79B8FF" },
    Token { name: "a-mag", value: "#C79BFF" },
    Token { name: "a-cyan", value: "#4FD6E0" },
    Token { name: "a-white", value: "#F0F4FA" },
    Token { name: "sel", value: "rgba(47,111,237,.28)" },
    Token { name: "sel-ink", value: "#141A22" },
    Token { name: "c-green", value: "#15803D" },
    Token { name: "c-amber", value: "#B45309" },
    Token { name: "c-red", value: "#DC2626" },
    Token { name: "c-orange", value: "#C2410C" },
    Token { name: "c-blue", value: "#2563EB" },
    Token { name: "c-purple", value: "#7C3AED" },
    Token { name: "c-teal", value: "#0F766E" },
    Token { name: "c-slate", value: "#475569" },
    Token { name: "c-pink", value: "#DB2777" },
    Token { name: "term-line", value: "#1A1E26" },
    Token { name: "term-strong", value: "#EAF0F8" },
    Token { name: "term-metric", value: "#D3DBE6" },
    Token { name: "term-tab-ink", value: "#E1E7F0" },
    Token { name: "term-tab-on", value: "#EDF2F9" },
    Token { name: "term-tab-line", value: "#1E232C" },
    Token { name: "term-danger", value: "#FF8A80" },
    Token { name: "term-accent", value: "#8CC2FF" },
    Token { name: "term-accent-fg", value: "#6FB2FF" },
    Token { name: "term-accent-ink", value: "#EAF3FF" },
    Token { name: "term-fg-bright", value: "#E6ECF4" },
    Token { name: "term-sel-ink", value: "#F0F4FA" },
    Token { name: "ink-on-color", value: "#FFFFFF" },
    Token { name: "seg-on", value: "#262B34" },
    Token { name: "wc-close", value: "#FF5F57" },
    Token { name: "wc-min", value: "#FEBC2E" },
    Token { name: "wc-max", value: "#28C840" },
    Token { name: "font-ui", value: "-apple-system,BlinkMacSystemFont,\"Segoe UI Variable Text\",\"Segoe UI\",Inter,system-ui,\"PingFang SC\",\"Microsoft YaHei UI\",\"Noto Sans SC\",sans-serif" },
    Token { name: "font-mono", value: "ui-monospace,\"Cascadia Mono\",\"SF Mono\",Menlo,Consolas,\"JetBrains Mono\",monospace" },
    Token { name: "fs-12", value: "12px" },
    Token { name: "fs-13", value: "13px" },
    Token { name: "fs-14", value: "14px" },
    Token { name: "fs-15", value: "15px" },
    Token { name: "fs-16", value: "16px" },
    Token { name: "fs-18", value: "18px" },
    Token { name: "fs-20", value: "20px" },
    Token { name: "term-fs", value: "12.5px" },
    Token { name: "term-fs-12", value: "12px" },
    Token { name: "term-fs-14", value: "14px" },
    Token { name: "term-fs-16", value: "16px" },
    Token { name: "term-fs-18", value: "18px" },
    Token { name: "term-fs-20", value: "20px" },
    Token { name: "sp-1", value: "4px" },
    Token { name: "sp-2", value: "8px" },
    Token { name: "sp-3", value: "12px" },
    Token { name: "sp-4", value: "16px" },
    Token { name: "sp-5", value: "24px" },
    Token { name: "sp-6", value: "32px" },
    Token { name: "sp-7", value: "48px" },
    Token { name: "card-head-h", value: "44px" },
    Token { name: "statusbar-h", value: "32px" },
    Token { name: "titlebar-h", value: "48px" },
    Token { name: "toolbar-h", value: "56px" },
    Token { name: "capsule-h", value: "48px" },
    Token { name: "win-mx", value: "clamp(16px,2.4vw,56px)" },
    Token { name: "win-my", value: "clamp(12px,1.7vh,24px)" },
    Token { name: "r-input", value: "8px" },
    Token { name: "r-card", value: "10px" },
    Token { name: "r-pop", value: "14px" },
    Token { name: "r-pill", value: "999px" },
    Token { name: "elev-0", value: "none" },
    Token { name: "elev-1", value: "0 1px 2px rgba(30,28,24,.06), 0 1px 1px rgba(30,28,24,.04)" },
    Token { name: "elev-2", value: "0 24px 60px rgba(30,28,24,.25)" },
    Token { name: "shadow-win", value: "0 30px 80px rgba(38,32,24,.26), inset 0 1px 0 rgba(255,255,255,.7)" },
    Token { name: "m-fast", value: "120ms" },
    Token { name: "m-base", value: "180ms" },
    Token { name: "m-slow", value: "240ms" },
    Token { name: "ease", value: "cubic-bezier(.2,0,0,1)" },
    Token { name: "ease-out", value: "cubic-bezier(.25,1,.5,1)" },
    Token { name: "risk-l0", value: "#123E9E" },
    Token { name: "risk-l1", value: "#116635" },
    Token { name: "risk-l2", value: "#7A3A06" },
    Token { name: "risk-l3", value: "#A32018" },
    Token { name: "risk-l3-ink", value: "#FFFFFF" },
    Token { name: "risk-u", value: "#7013A8" },
    Token { name: "code-bg", value: "rgba(47,111,237,.09)" },
    Token { name: "code-bd", value: "rgba(47,111,237,.18)" },
    Token { name: "code-fg", value: "#1D4FD8" },
];

/// Resolved token list for a theme.
pub fn tokens(theme: Theme) -> &'static [Token] {
    match theme {
        Theme::Dark => DARK,
        Theme::Light => LIGHT,
    }
}

/// Look up a token value by kebab-case name.
pub fn value(theme: Theme, name: &str) -> Option<&'static str> {
    for t in tokens(theme) {
        if t.name == name {
            return Some(t.value);
        }
    }
    None
}

/// Per-token constants: kebab-case name -> SCREAMING_SNAKE_CASE (dark theme).
pub mod dark {
    pub const CANVAS: &str = "#08090C";
    pub const SURFACE: &str = "#17191F";
    pub const RAISED: &str = "#1E2129";
    pub const SUNKEN: &str = "#121419";
    pub const BORDER: &str = "#2A2F38";
    pub const BORDER_SOFT: &str = "#20242C";
    pub const TEXT: &str = "#E7E9EE";
    pub const TEXT_2: &str = "#A6ADBA";
    pub const TEXT_3: &str = "#949CAA";
    pub const GHOST: &str = "#868E9C";
    pub const ACCENT: &str = "#4A9EFF";
    pub const ACCENT_INK: &str = "#06121F";
    pub const ACCENT_DIM: &str = "rgba(74,158,255,.12)";
    pub const ACCENT_DIM2: &str = "rgba(74,158,255,.20)";
    pub const ACCENT_LINE: &str = "rgba(74,158,255,.35)";
    pub const HOVER: &str = "rgba(255,255,255,.045)";
    pub const HOVER_2: &str = "rgba(255,255,255,.075)";
    pub const OVERLAY: &str = "rgba(6,7,10,.62)";
    pub const WALL_A: &str = "#243244";
    pub const WALL_B: &str = "#5D6470";
    pub const WALL_C: &str = "#C69A63";
    pub const WALL_D: &str = "#E0B478";
    pub const WALL_E: &str = "#8A5A2B";
    pub const MARK_A: &str = "#2A63D8";
    pub const MARK_B: &str = "#1E4FC4";
    pub const MARK_C: &str = "#14347F";
    pub const TERM_BG: &str = "#0B0D11";
    pub const TERM_BG2: &str = "#0E1116";
    pub const TERM_FG: &str = "#C9D1DC";
    pub const TERM_DIM: &str = "#9AA4B2";
    pub const TERM_MUT: &str = "#A3ADBB";
    pub const A_RED: &str = "#FF6B62";
    pub const A_GREEN: &str = "#4ED17A";
    pub const A_YELLOW: &str = "#E8B93B";
    pub const A_BLUE: &str = "#79B8FF";
    pub const A_MAG: &str = "#C79BFF";
    pub const A_CYAN: &str = "#4FD6E0";
    pub const A_WHITE: &str = "#F0F4FA";
    pub const SEL: &str = "rgba(74,158,255,.28)";
    pub const SEL_INK: &str = "#F0F4FA";
    pub const C_GREEN: &str = "#22C55E";
    pub const C_AMBER: &str = "#D97706";
    pub const C_RED: &str = "#EF4444";
    pub const C_ORANGE: &str = "#F97316";
    pub const C_BLUE: &str = "#3B82F6";
    pub const C_PURPLE: &str = "#A855F7";
    pub const C_TEAL: &str = "#14B8A6";
    pub const C_SLATE: &str = "#5B6B7C";
    pub const C_PINK: &str = "#EC4899";
    pub const TERM_LINE: &str = "#1A1E26";
    pub const TERM_STRONG: &str = "#EAF0F8";
    pub const TERM_METRIC: &str = "#D3DBE6";
    pub const TERM_TAB_INK: &str = "#E1E7F0";
    pub const TERM_TAB_ON: &str = "#EDF2F9";
    pub const TERM_TAB_LINE: &str = "#1E232C";
    pub const TERM_DANGER: &str = "#FF8A80";
    pub const TERM_ACCENT: &str = "#8CC2FF";
    pub const TERM_ACCENT_FG: &str = "#6FB2FF";
    pub const TERM_ACCENT_INK: &str = "#EAF3FF";
    pub const TERM_FG_BRIGHT: &str = "#E6ECF4";
    pub const TERM_SEL_INK: &str = "#F0F4FA";
    pub const INK_ON_COLOR: &str = "#FFFFFF";
    pub const SEG_ON: &str = "#262B34";
    pub const WC_CLOSE: &str = "#FF5F57";
    pub const WC_MIN: &str = "#FEBC2E";
    pub const WC_MAX: &str = "#28C840";
    pub const FONT_UI: &str = "-apple-system,BlinkMacSystemFont,\"Segoe UI Variable Text\",\"Segoe UI\",Inter,system-ui,\"PingFang SC\",\"Microsoft YaHei UI\",\"Noto Sans SC\",sans-serif";
    pub const FONT_MONO: &str = "ui-monospace,\"Cascadia Mono\",\"SF Mono\",Menlo,Consolas,\"JetBrains Mono\",monospace";
    pub const FS_12: &str = "12px";
    pub const FS_13: &str = "13px";
    pub const FS_14: &str = "14px";
    pub const FS_15: &str = "15px";
    pub const FS_16: &str = "16px";
    pub const FS_18: &str = "18px";
    pub const FS_20: &str = "20px";
    pub const TERM_FS: &str = "12.5px";
    pub const TERM_FS_12: &str = "12px";
    pub const TERM_FS_14: &str = "14px";
    pub const TERM_FS_16: &str = "16px";
    pub const TERM_FS_18: &str = "18px";
    pub const TERM_FS_20: &str = "20px";
    pub const SP_1: &str = "4px";
    pub const SP_2: &str = "8px";
    pub const SP_3: &str = "12px";
    pub const SP_4: &str = "16px";
    pub const SP_5: &str = "24px";
    pub const SP_6: &str = "32px";
    pub const SP_7: &str = "48px";
    pub const CARD_HEAD_H: &str = "44px";
    pub const STATUSBAR_H: &str = "32px";
    pub const TITLEBAR_H: &str = "48px";
    pub const TOOLBAR_H: &str = "56px";
    pub const CAPSULE_H: &str = "48px";
    pub const WIN_MX: &str = "clamp(16px,2.4vw,56px)";
    pub const WIN_MY: &str = "clamp(12px,1.7vh,24px)";
    pub const R_INPUT: &str = "8px";
    pub const R_CARD: &str = "10px";
    pub const R_POP: &str = "14px";
    pub const R_PILL: &str = "999px";
    pub const ELEV_0: &str = "none";
    pub const ELEV_1: &str = "0 1px 2px rgba(0,0,0,.34)";
    pub const ELEV_2: &str = "0 24px 64px rgba(0,0,0,.6)";
    pub const SHADOW_WIN: &str = "0 32px 90px rgba(0,0,0,.62), inset 0 1px 0 rgba(255,255,255,.04)";
    pub const M_FAST: &str = "120ms";
    pub const M_BASE: &str = "180ms";
    pub const M_SLOW: &str = "240ms";
    pub const EASE: &str = "cubic-bezier(.2,0,0,1)";
    pub const EASE_OUT: &str = "cubic-bezier(.25,1,.5,1)";
    pub const RISK_L0: &str = "#7FB8FF";
    pub const RISK_L1: &str = "#22C55E";
    pub const RISK_L2: &str = "#F0A23C";
    pub const RISK_L3: &str = "#FF8578";
    pub const RISK_L3_INK: &str = "#1A0B0A";
    pub const RISK_U: &str = "#C9A0FF";
    pub const CODE_BG: &str = "rgba(74,158,255,.14)";
    pub const CODE_BD: &str = "rgba(74,158,255,.22)";
    pub const CODE_FG: &str = "#9CC7FF";
}

/// Per-token constants: kebab-case name -> SCREAMING_SNAKE_CASE (light theme).
pub mod light {
    pub const CANVAS: &str = "#F6F5F2";
    pub const SURFACE: &str = "#FFFFFF";
    pub const RAISED: &str = "#F1F0EC";
    pub const SUNKEN: &str = "#F7F7F5";
    pub const BORDER: &str = "#E6E4DF";
    pub const BORDER_SOFT: &str = "#EFEDE8";
    pub const TEXT: &str = "#1B1D21";
    pub const TEXT_2: &str = "#59616D";
    pub const TEXT_3: &str = "#5E6571";
    pub const GHOST: &str = "#7C8493";
    pub const ACCENT: &str = "#245BC9";
    pub const ACCENT_INK: &str = "#FFFFFF";
    pub const ACCENT_DIM: &str = "rgba(47,111,237,.10)";
    pub const ACCENT_DIM2: &str = "rgba(47,111,237,.17)";
    pub const ACCENT_LINE: &str = "rgba(47,111,237,.32)";
    pub const HOVER: &str = "rgba(20,22,26,.045)";
    pub const HOVER_2: &str = "rgba(20,22,26,.075)";
    pub const OVERLAY: &str = "rgba(48,44,38,.35)";
    pub const WALL_A: &str = "#7F8A94";
    pub const WALL_B: &str = "#BFC2BE";
    pub const WALL_C: &str = "#E9C79B";
    pub const WALL_D: &str = "#F0CFA2";
    pub const WALL_E: &str = "#B98A55";
    pub const MARK_A: &str = "#2A63D8";
    pub const MARK_B: &str = "#1E4FC4";
    pub const MARK_C: &str = "#14347F";
    pub const TERM_BG: &str = "#0B0D11";
    pub const TERM_BG2: &str = "#0E1116";
    pub const TERM_FG: &str = "#C9D1DC";
    pub const TERM_DIM: &str = "#9AA4B2";
    pub const TERM_MUT: &str = "#A3ADBB";
    pub const A_RED: &str = "#FF6B62";
    pub const A_GREEN: &str = "#4ED17A";
    pub const A_YELLOW: &str = "#E8B93B";
    pub const A_BLUE: &str = "#79B8FF";
    pub const A_MAG: &str = "#C79BFF";
    pub const A_CYAN: &str = "#4FD6E0";
    pub const A_WHITE: &str = "#F0F4FA";
    pub const SEL: &str = "rgba(47,111,237,.28)";
    pub const SEL_INK: &str = "#141A22";
    pub const C_GREEN: &str = "#15803D";
    pub const C_AMBER: &str = "#B45309";
    pub const C_RED: &str = "#DC2626";
    pub const C_ORANGE: &str = "#C2410C";
    pub const C_BLUE: &str = "#2563EB";
    pub const C_PURPLE: &str = "#7C3AED";
    pub const C_TEAL: &str = "#0F766E";
    pub const C_SLATE: &str = "#475569";
    pub const C_PINK: &str = "#DB2777";
    pub const TERM_LINE: &str = "#1A1E26";
    pub const TERM_STRONG: &str = "#EAF0F8";
    pub const TERM_METRIC: &str = "#D3DBE6";
    pub const TERM_TAB_INK: &str = "#E1E7F0";
    pub const TERM_TAB_ON: &str = "#EDF2F9";
    pub const TERM_TAB_LINE: &str = "#1E232C";
    pub const TERM_DANGER: &str = "#FF8A80";
    pub const TERM_ACCENT: &str = "#8CC2FF";
    pub const TERM_ACCENT_FG: &str = "#6FB2FF";
    pub const TERM_ACCENT_INK: &str = "#EAF3FF";
    pub const TERM_FG_BRIGHT: &str = "#E6ECF4";
    pub const TERM_SEL_INK: &str = "#F0F4FA";
    pub const INK_ON_COLOR: &str = "#FFFFFF";
    pub const SEG_ON: &str = "#262B34";
    pub const WC_CLOSE: &str = "#FF5F57";
    pub const WC_MIN: &str = "#FEBC2E";
    pub const WC_MAX: &str = "#28C840";
    pub const FONT_UI: &str = "-apple-system,BlinkMacSystemFont,\"Segoe UI Variable Text\",\"Segoe UI\",Inter,system-ui,\"PingFang SC\",\"Microsoft YaHei UI\",\"Noto Sans SC\",sans-serif";
    pub const FONT_MONO: &str = "ui-monospace,\"Cascadia Mono\",\"SF Mono\",Menlo,Consolas,\"JetBrains Mono\",monospace";
    pub const FS_12: &str = "12px";
    pub const FS_13: &str = "13px";
    pub const FS_14: &str = "14px";
    pub const FS_15: &str = "15px";
    pub const FS_16: &str = "16px";
    pub const FS_18: &str = "18px";
    pub const FS_20: &str = "20px";
    pub const TERM_FS: &str = "12.5px";
    pub const TERM_FS_12: &str = "12px";
    pub const TERM_FS_14: &str = "14px";
    pub const TERM_FS_16: &str = "16px";
    pub const TERM_FS_18: &str = "18px";
    pub const TERM_FS_20: &str = "20px";
    pub const SP_1: &str = "4px";
    pub const SP_2: &str = "8px";
    pub const SP_3: &str = "12px";
    pub const SP_4: &str = "16px";
    pub const SP_5: &str = "24px";
    pub const SP_6: &str = "32px";
    pub const SP_7: &str = "48px";
    pub const CARD_HEAD_H: &str = "44px";
    pub const STATUSBAR_H: &str = "32px";
    pub const TITLEBAR_H: &str = "48px";
    pub const TOOLBAR_H: &str = "56px";
    pub const CAPSULE_H: &str = "48px";
    pub const WIN_MX: &str = "clamp(16px,2.4vw,56px)";
    pub const WIN_MY: &str = "clamp(12px,1.7vh,24px)";
    pub const R_INPUT: &str = "8px";
    pub const R_CARD: &str = "10px";
    pub const R_POP: &str = "14px";
    pub const R_PILL: &str = "999px";
    pub const ELEV_0: &str = "none";
    pub const ELEV_1: &str = "0 1px 2px rgba(30,28,24,.06), 0 1px 1px rgba(30,28,24,.04)";
    pub const ELEV_2: &str = "0 24px 60px rgba(30,28,24,.25)";
    pub const SHADOW_WIN: &str = "0 30px 80px rgba(38,32,24,.26), inset 0 1px 0 rgba(255,255,255,.7)";
    pub const M_FAST: &str = "120ms";
    pub const M_BASE: &str = "180ms";
    pub const M_SLOW: &str = "240ms";
    pub const EASE: &str = "cubic-bezier(.2,0,0,1)";
    pub const EASE_OUT: &str = "cubic-bezier(.25,1,.5,1)";
    pub const RISK_L0: &str = "#123E9E";
    pub const RISK_L1: &str = "#116635";
    pub const RISK_L2: &str = "#7A3A06";
    pub const RISK_L3: &str = "#A32018";
    pub const RISK_L3_INK: &str = "#FFFFFF";
    pub const RISK_U: &str = "#7013A8";
    pub const CODE_BG: &str = "rgba(47,111,237,.09)";
    pub const CODE_BD: &str = "rgba(47,111,237,.18)";
    pub const CODE_FG: &str = "#1D4FD8";
}
